//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Активности> Активности { get; set; }
        public virtual DbSet<Города> Города { get; set; }
        public virtual DbSet<ЖюриАктивности> ЖюриАктивности { get; set; }
        public virtual DbSet<Мероприятия> Мероприятия { get; set; }
        public virtual DbSet<Направления> Направления { get; set; }
        public virtual DbSet<Оценки> Оценки { get; set; }
        public virtual DbSet<Пол> Пол { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Роли> Роли { get; set; }
        public virtual DbSet<РолиЖюри> РолиЖюри { get; set; }
        public virtual DbSet<Страны> Страны { get; set; }
        public virtual DbSet<УчастникиАктивностей> УчастникиАктивностей { get; set; }
    }
}
