//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЖюриАктивности
    {
        public int Id { get; set; }
        public int АктивностьId { get; set; }
        public int ЖюриId { get; set; }
        public int РольId { get; set; }
    
        public virtual Активности Активности { get; set; }
        public virtual Пользователи Пользователи { get; set; }
        public virtual РолиЖюри РолиЖюри { get; set; }
    }
}
