//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Мероприятия
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Мероприятия()
        {
            this.Активности = new HashSet<Активности>();
        }
    
        public int Id { get; set; }
        public string Название { get; set; }
        public System.DateTime ДатаНачала { get; set; }
        public int ДлительностьДней { get; set; }
        public int ГородId { get; set; }
        public int НаправлениеId { get; set; }
        public Nullable<int> ПобедительId { get; set; }
        public string Фото { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Активности> Активности { get; set; }
        public virtual Города Города { get; set; }
        public virtual Направления Направления { get; set; }
        public virtual Пользователи Пользователи { get; set; }
    }
}
