//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оценки
    {
        public int Id { get; set; }
        public int ЖюриАктивностиId { get; set; }
        public int УчастникАктивностиId { get; set; }
        public int Оценка { get; set; }
        public string Комментарий { get; set; }
        public System.DateTime ДатаОценки { get; set; }
    
        public virtual ЖюриАктивности ЖюриАктивности { get; set; }
        public virtual УчастникиАктивностей УчастникиАктивностей { get; set; }
    }
}
