//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Пользователи()
        {
            this.Активности = new HashSet<Активности>();
            this.ЖюриАктивности = new HashSet<ЖюриАктивности>();
            this.Мероприятия = new HashSet<Мероприятия>();
        }
    
        public int Id { get; set; }
        public string ФИО { get; set; }
        public string Почта { get; set; }
        public System.DateTime ДатаРождения { get; set; }
        public int СтранаId { get; set; }
        public string Телефон { get; set; }
        public string Пароль { get; set; }
        public string Фото { get; set; }
        public int ПолId { get; set; }
        public int РольId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Активности> Активности { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЖюриАктивности> ЖюриАктивности { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Мероприятия> Мероприятия { get; set; }
        public virtual Пол Пол { get; set; }
        public virtual Роли Роли { get; set; }
        public virtual Страны Страны { get; set; }
    }
}
