//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class УчастникиАктивностей
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public УчастникиАктивностей()
        {
            this.Оценки = new HashSet<Оценки>();
        }
    
        public int Id { get; set; }
        public int ПользовательId { get; set; }
        public int АктивностьId { get; set; }
    
        public virtual Активности Активности { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Оценки> Оценки { get; set; }
        public virtual Пользователи Пользователи { get; set; }
    }
}
